CREATE DATABASE comments;
use comments;

CREATE TABLE comments (
  id MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  author VARCHAR(255) NULL DEFAULT NULL,
  date DATE NULL DEFAULT NULL,
  content TEXT NULL DEFAULT NULL,
  author_email VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
);
